[package]
name = "gerust_router"
version = "0.1.0"
authors = ["Florian Gilcher <florian.gilcher@asquera.de>"]

[dependencies]
url = "*"
gerust_routing = { path = "../gerust_routing" }
futures = "0.1.13"